[package]
name = "pliego-css-lsp"
description = "Language Server Protocol transport for PliegoCSS"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license-file.workspace = true
repository.workspace = true
authors.workspace = true
readme = "README.md"
keywords.workspace = true
categories.workspace = true

[[bin]]
name = "pliego-css-lsp"
path = "src/main.rs"

[dependencies]
pliego-css-parser.workspace = true
pliego-css-source.workspace = true
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
sha2 = "0.10"

[lints]
workspace = true
