[package]
name = "pliego-css-parser"
description = "Utility grammar parser for PliegoCSS"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
homepage.workspace = true
documentation = "https://docs.rs/pliego-css-parser"
publish.workspace = true
readme = "README.md"
keywords.workspace = true
categories.workspace = true

[dependencies]
pliego-css-ir.workspace = true

[lints]
workspace = true
