[package]
name = "pliego-css-publication"
description = "Rollback-capable filesystem publication primitives for PliegoCSS tooling"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
homepage.workspace = true
documentation = "https://docs.rs/pliego-css-publication"
publish.workspace = true
readme = "README.md"
keywords.workspace = true
categories.workspace = true

[dependencies]
fs2 = "0.4.3"
same-file = "1.0.6"

[target.'cfg(unix)'.dependencies]
libc = "0.2.186"

[lints]
workspace = true
