//! Read-only audit projection into canonical control artifacts.

mod accessibility;
mod sarif;

pub use accessibility::*;
pub use sarif::render_sarif;

use std::collections::{BTreeMap, BTreeSet};

use crate::{
    AdapterIdentity, ArtifactReference, BUILD_RECEIPT_FILE, BUILD_RECEIPT_KIND, BackendIdentity,
    BuildReceipt, CONTROL_MANIFEST_FILE, CONTROL_MANIFEST_KIND, CONTROL_SCHEMA_VERSION,
    CheckStatus, CompatibilityData, ControlManifest, Decision, DecisionAction, InputFile,
    ManifestInputs, MeasurementState, OutputArtifact, ReceiptCheck, ReceiptDecisionSummary,
    ReceiptExpectation, ReceiptFindingSummary, ReceiptInputs, ReceiptResult, RuleMeasurements,
    TOKEN_GRAPH_FILE, TargetIdentity, TokenMeasurements, ToolIdentity, ViolationSummary,
    content_hash,
};
use pliego_css_build::artifacts::{
    CompatibilityProfile, FINDING_SCHEMA_VERSION, FindingDocument, build_compatibility_policy,
};
use pliego_css_config::{
    BudgetPolicy, BudgetSubject, CssBudgetMetrics, CssSpecificity, TokenExpression, TokenGraph,
    TokenGraphProjection, parse_token_graph,
};
use pliego_css_ir::{TokenId, TokenKind};
use pliego_css_theme::ThemeRegistry;
use serde::Serialize;
use serde_json::{Map, Value};

/// Fixed canonical findings filename adjacent to the manifest and receipt.
pub const FINDINGS_FILE: &str = "pliego.css.findings.json";

#[derive(Clone, Copy)]
/// Exact logical input projected into the control ledger.
pub struct AuditSourceInput<'a> {
    /// Portable workspace-relative identity.
    pub logical_path: &'a str,
    /// Canonical input role.
    pub role: &'a str,
    /// Exact bytes read by the producer.
    pub bytes: &'a [u8],
}

#[derive(Clone, Copy)]
/// Exact source-map artifact referenced by one generated output.
pub struct ControlSourceMapInput<'a> {
    /// Portable logical source-map path.
    pub file: &'a str,
    /// Exact canonical source-map bytes.
    pub bytes: &'a [u8],
}

#[derive(Clone, Copy)]
/// Generated output projected into the control ledger.
pub struct ControlOutputInput<'a> {
    /// Portable logical output path.
    pub file: &'a str,
    /// Canonical output role.
    pub role: &'a str,
    /// Canonical media type.
    pub media_type: &'a str,
    /// Exact generated bytes.
    pub bytes: &'a [u8],
    /// Optional exact source-map artifact emitted in the same control group.
    pub source_map: Option<ControlSourceMapInput<'a>>,
    /// Logical paths of related outputs.
    pub relationships: &'a [String],
}

#[derive(Clone, Copy)]
/// One authored origin eligible for a generated source-map segment.
pub struct SourceMapOrigin<'a> {
    /// Portable logical input path, absent for virtual CLI origins.
    pub file: Option<&'a str>,
    /// Exact UTF-8 byte offset in the input snapshot.
    pub byte_start: Option<usize>,
}

#[derive(Clone, Copy)]
/// One generated class and its normalized authored origins.
pub struct SourceMapStyle<'a> {
    /// Exact emitted class name without the leading dot.
    pub class_name: &'a str,
    /// Deterministically ordered authored origins.
    pub origins: &'a [SourceMapOrigin<'a>],
}

#[derive(Serialize)]
struct SourceMapDocument<'a> {
    version: u8,
    sources: &'a [String],
    names: [String; 0],
    mappings: String,
}

#[derive(Clone, Debug, Eq, Ord, PartialEq, PartialOrd)]
struct SourceMapSegment {
    generated_line: usize,
    generated_column: usize,
    source_file: String,
    original_line: usize,
    original_column: usize,
}

struct Utf8Source<'a> {
    text: &'a str,
    line_starts: Vec<usize>,
}

/// Builds a deterministic Source Map v3 from final CSS classes to exact authored snapshots.
///
/// Standard source maps encode one origin per generated segment. This projection therefore selects
/// the first normalized origin that resolves in the exact source ledger; the specialized style
/// manifest remains authoritative for complete many-to-many provenance.
///
/// # Errors
///
/// Returns an error when inputs are duplicate or non-UTF-8, an origin escapes its exact snapshot,
/// a generated class is absent from final CSS, or the canonical document cannot be encoded.
pub fn build_css_source_map(
    css: &str,
    styles: &[SourceMapStyle<'_>],
    inputs: &[AuditSourceInput<'_>],
) -> Result<Vec<u8>, String> {
    let mut source_ledger = BTreeMap::new();
    let mut virtual_source = None;
    for input in inputs {
        let text = std::str::from_utf8(input.bytes).map_err(|error| {
            format!(
                "source-map input `{}` is not valid UTF-8: {error}",
                input.logical_path
            )
        })?;
        let source = Utf8Source {
            text,
            line_starts: line_starts(text),
        };
        if source_ledger.insert(input.logical_path, source).is_some() {
            return Err(format!(
                "source-map input `{}` is duplicated",
                input.logical_path
            ));
        }
        if input.role == "cli-source" && virtual_source.is_none() {
            virtual_source = Some(input.logical_path);
        }
    }
    let generated_lines = line_starts(css);
    let mut segments = Vec::new();
    for style in styles {
        let (source_file, source_offset) =
            select_source_map_origin(style, &source_ledger, virtual_source)?;
        let source = source_ledger
            .get(source_file.as_str())
            .ok_or_else(|| "selected source-map origin escaped the exact ledger".to_owned())?;
        let (original_line, original_column) =
            utf16_position(source.text, &source.line_starts, source_offset)?;
        let needle = format!(".{}", style.class_name);
        let mut matched = false;
        for (generated_offset, _) in css.match_indices(&needle) {
            matched = true;
            let (generated_line, generated_column) =
                utf16_position(css, &generated_lines, generated_offset)?;
            segments.push(SourceMapSegment {
                generated_line,
                generated_column,
                source_file: source_file.clone(),
                original_line,
                original_column,
            });
        }
        if !matched {
            return Err(format!(
                "source-map class `{}` is absent from final CSS",
                style.class_name
            ));
        }
    }
    segments.sort();
    if segments.windows(2).any(|pair| {
        pair[0].generated_line == pair[1].generated_line
            && pair[0].generated_column == pair[1].generated_column
    }) {
        return Err("source-map has conflicting origins at one generated position".to_owned());
    }
    let sources = segments
        .iter()
        .map(|segment| segment.source_file.clone())
        .collect::<BTreeSet<_>>()
        .into_iter()
        .collect::<Vec<_>>();
    let source_indices = sources
        .iter()
        .enumerate()
        .map(|(index, source)| (source.as_str(), index))
        .collect::<BTreeMap<_, _>>();
    let mappings = encode_mappings(&segments, &source_indices)?;
    let mut bytes = serde_json::to_vec(&SourceMapDocument {
        version: 3,
        sources: &sources,
        names: [],
        mappings,
    })
    .map_err(|error| format!("cannot encode canonical CSS source map: {error}"))?;
    bytes.push(b'\n');
    Ok(bytes)
}

fn select_source_map_origin(
    style: &SourceMapStyle<'_>,
    source_ledger: &BTreeMap<&str, Utf8Source<'_>>,
    virtual_source: Option<&str>,
) -> Result<(String, usize), String> {
    if let Some((file, offset)) = style
        .origins
        .iter()
        .filter_map(|origin| Some((origin.file?, origin.byte_start?)))
        .find(|(file, offset)| {
            source_ledger
                .get(file)
                .is_some_and(|source| valid_utf8_offset(source.text, *offset))
        })
    {
        return Ok((file.to_owned(), offset));
    }
    let has_virtual_origin = style
        .origins
        .iter()
        .any(|origin| origin.file.is_none() && origin.byte_start.is_none());
    virtual_source
        .filter(|_| has_virtual_origin)
        .map(|file| (file.to_owned(), 0))
        .ok_or_else(|| {
            format!(
                "source-map class `{}` has no origin in the exact source ledger",
                style.class_name
            )
        })
}

fn line_starts(text: &str) -> Vec<usize> {
    let mut starts = vec![0];
    starts.extend(
        text.as_bytes()
            .iter()
            .enumerate()
            .filter_map(|(index, byte)| (*byte == b'\n').then_some(index + 1)),
    );
    starts
}

fn valid_utf8_offset(text: &str, offset: usize) -> bool {
    offset <= text.len() && text.is_char_boundary(offset)
}

fn utf16_position(text: &str, starts: &[usize], offset: usize) -> Result<(usize, usize), String> {
    if !valid_utf8_offset(text, offset) {
        return Err(format!(
            "source-map byte offset {offset} is outside a UTF-8 character boundary"
        ));
    }
    let line = starts.partition_point(|start| *start <= offset) - 1;
    let column = text[starts[line]..offset].encode_utf16().count();
    Ok((line, column))
}

fn encode_mappings(
    segments: &[SourceMapSegment],
    source_indices: &BTreeMap<&str, usize>,
) -> Result<String, String> {
    let mut output = String::new();
    let mut generated_line = 0usize;
    let mut generated_column = 0i64;
    let mut previous_source = 0i64;
    let mut previous_original_line = 0i64;
    let mut previous_original_column = 0i64;
    let mut first_on_line = true;
    for segment in segments {
        while generated_line < segment.generated_line {
            output.push(';');
            generated_line += 1;
            generated_column = 0;
            first_on_line = true;
        }
        if !first_on_line {
            output.push(',');
        }
        let column = i64::try_from(segment.generated_column)
            .map_err(|_| "source-map generated column exceeds i64".to_owned())?;
        let source_index = source_indices
            .get(segment.source_file.as_str())
            .ok_or_else(|| "source-map segment references an unindexed source".to_owned())?;
        let source = i64::try_from(*source_index)
            .map_err(|_| "source-map source index exceeds i64".to_owned())?;
        let original_line = i64::try_from(segment.original_line)
            .map_err(|_| "source-map original line exceeds i64".to_owned())?;
        let original_column = i64::try_from(segment.original_column)
            .map_err(|_| "source-map original column exceeds i64".to_owned())?;
        encode_vlq(column - generated_column, &mut output);
        encode_vlq(source - previous_source, &mut output);
        encode_vlq(original_line - previous_original_line, &mut output);
        encode_vlq(original_column - previous_original_column, &mut output);
        generated_column = column;
        previous_source = source;
        previous_original_line = original_line;
        previous_original_column = original_column;
        first_on_line = false;
    }
    Ok(output)
}

fn encode_vlq(value: i64, output: &mut String) {
    const BASE64: &[u8; 64] = b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
    let mut encoded = (value.unsigned_abs() << 1) | u64::from(value.is_negative());
    loop {
        let mut digit = u8::try_from(encoded & 31).expect("base64 VLQ digit fits u8");
        encoded >>= 5;
        if encoded != 0 {
            digit |= 32;
        }
        output.push(char::from(BASE64[usize::from(digit)]));
        if encoded == 0 {
            break;
        }
    }
}

#[derive(Clone, Copy)]
/// Honest token observation supplied by the producer for one control group.
pub enum TokenObservationInput<'a> {
    /// Complete measurements for the producer's declared graph boundary.
    Measured(&'a TokenMeasurements),
    /// Deterministic reason why no typed token graph was available.
    Unavailable(&'a str),
}

#[derive(Clone, Copy, Debug, Eq, Ord, PartialEq, PartialOrd)]
/// One typed token referenced by retained generated semantics.
pub struct FlatTokenReference {
    kind: TokenKind,
    id: TokenId,
}

impl FlatTokenReference {
    /// Creates a reference that must resolve in the active flat registry.
    #[must_use]
    pub const fn new(kind: TokenKind, id: TokenId) -> Self {
        Self { kind, id }
    }
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
struct FlatTokenGraph<'a> {
    schema_version: u8,
    tokens: Vec<FlatTokenNode<'a>>,
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
struct FlatTokenNode<'a> {
    kind: &'static str,
    token_id: String,
    name: &'a str,
    value: &'a str,
}

/// Projects one active flat registry plus retained references into measured control evidence.
///
/// # Errors
///
/// Returns an error when a retained reference is absent from the registry, a count cannot fit the
/// wire contract, or the canonical graph cannot be encoded.
pub fn build_flat_token_measurements(
    theme: &ThemeRegistry,
    used: &BTreeSet<FlatTokenReference>,
) -> Result<TokenMeasurements, String> {
    let declared = theme
        .tokens()
        .iter()
        .map(|token| FlatTokenReference::new(token.kind, token.id))
        .collect::<BTreeSet<_>>();
    if !used.is_subset(&declared) {
        return Err("compiled token usage escaped the active typed registry".into());
    }
    let graph = FlatTokenGraph {
        schema_version: 1,
        tokens: theme
            .tokens()
            .iter()
            .map(|token| FlatTokenNode {
                kind: token_kind_name(token.kind),
                token_id: format!("{:08x}", token.id.get()),
                name: &token.name,
                value: &token.value,
            })
            .collect(),
    };
    let graph = serde_json::to_vec(&graph)
        .map_err(|error| format!("cannot encode flat token graph: {error}"))?;
    let tokens =
        u64::try_from(declared.len()).map_err(|_| "declared token count exceeds u64".to_owned())?;
    let used = u64::try_from(used.len()).map_err(|_| "used token count exceeds u64".to_owned())?;
    let coverage = u16::try_from(
        used.saturating_mul(10_000)
            .checked_div(tokens)
            .unwrap_or_default(),
    )
    .map_err(|_| "token coverage exceeds 10000 basis points".to_owned())?;
    Ok(TokenMeasurements {
        observation: MeasurementState::Measured,
        unavailable_reason: None,
        graph_version: Some("pliegocss-flat-token-graph/1".to_owned()),
        graph_hash: Some(content_hash(&graph)),
        tokens,
        aliases: 0,
        derived_values: 0,
        themes: 1,
        coverage_basis_points: Some(coverage),
        cycles: 0,
        contrast_pairs: 0,
        deprecations: 0,
        dtcg_adapter: None,
        dtcg_inventory: BTreeMap::new(),
    })
}

/// Projects a canonical internal token graph plus one exact resolution into measured evidence.
///
/// Coverage follows retained token references through the winning alias/derived dependency graph.
/// The graph hash excludes build usage, so changing only retained styles changes coverage without
/// changing graph identity.
///
/// # Errors
///
/// Returns an error when the graph is noncanonical, the selected resolution disagrees with the
/// active registry, a dependency projection is malformed, or compiled usage escapes the registry.
pub fn build_token_graph_measurements(
    graph: &TokenGraph,
    selections: &BTreeMap<String, String>,
    theme: &ThemeRegistry,
    used: &BTreeSet<FlatTokenReference>,
) -> Result<TokenMeasurements, String> {
    let graph_bytes = graph
        .to_canonical_json()
        .map_err(|error| format!("cannot encode token graph: {error}"))?;
    let resolution = graph
        .theme(selections)
        .ok_or_else(|| "token graph has no theme for the selected resolver inputs".to_owned())?;
    let theme_id = format!("{:032x}", theme.id().get());
    if resolution.theme_id != theme_id {
        return Err("token graph resolution disagrees with the active ThemeId".into());
    }
    let declared = theme
        .tokens()
        .iter()
        .map(|token| FlatTokenReference::new(token.kind, token.id))
        .collect::<BTreeSet<_>>();
    if !used.is_subset(&declared) {
        return Err("compiled token usage escaped the active typed registry".into());
    }
    validate_resolved_graph_tokens(resolution, theme)?;
    let coverage = graph_coverage(graph, resolution, &declared, used)?;
    let tokens = count_u64(declared.len(), "declared token")?;
    let covered = count_u64(coverage.covered, "covered token")?;
    let coverage_basis_points = u16::try_from(
        covered
            .saturating_mul(10_000)
            .checked_div(tokens)
            .unwrap_or_default(),
    )
    .map_err(|_| "token coverage exceeds 10000 basis points".to_owned())?;
    Ok(TokenMeasurements {
        observation: MeasurementState::Measured,
        unavailable_reason: None,
        graph_version: Some(graph.graph_version.clone()),
        graph_hash: Some(content_hash(&graph_bytes)),
        tokens,
        aliases: count_u64(coverage.aliases, "alias")?,
        derived_values: count_u64(coverage.derived_values, "derived value")?,
        themes: count_u64(graph.themes.len(), "theme")?,
        coverage_basis_points: Some(coverage_basis_points),
        cycles: 0,
        contrast_pairs: 0,
        deprecations: count_u64(coverage.deprecations, "deprecated token")?,
        dtcg_adapter: graph.adapter.as_ref().map(|adapter| AdapterIdentity {
            name: adapter.name.clone(),
            version: adapter.version.clone(),
        }),
        dtcg_inventory: resolution.dtcg_inventory.clone(),
    })
}

/// Projects a canonical token graph as audit evidence without claiming generated-style coverage.
///
/// Unlike [`build_token_graph_measurements`], a standards-CSS audit has no compiler-owned token-use
/// set or single active theme. This projection therefore counts the union of declared projected
/// tokens across every validated theme, records zero coverage, and carries the number of explicit
/// contrast relationships evaluated by the accessibility policy. It never infers token use from
/// CSS custom-property spelling.
///
/// # Errors
///
/// Returns an error when canonical graph serialization or any count exceeds its wire type.
pub fn build_audit_token_graph_measurements(
    graph: &TokenGraph,
    contrast_pairs: u64,
) -> Result<TokenMeasurements, String> {
    let graph_bytes = graph
        .to_canonical_json()
        .map_err(|error| format!("cannot encode audit token graph: {error}"))?;
    let declared = graph
        .themes
        .iter()
        .flat_map(|theme| &theme.tokens)
        .map(|token| (token.kind.as_str(), token.token_id.as_str()))
        .collect::<BTreeSet<_>>();
    Ok(TokenMeasurements {
        observation: MeasurementState::Measured,
        unavailable_reason: None,
        graph_version: Some(graph.graph_version.clone()),
        graph_hash: Some(content_hash(&graph_bytes)),
        tokens: count_u64(declared.len(), "audit declared token")?,
        aliases: graph.aliases(),
        derived_values: graph.derived_values(),
        themes: count_u64(graph.themes.len(), "audit token theme")?,
        coverage_basis_points: Some(0),
        cycles: 0,
        contrast_pairs,
        deprecations: graph.deprecations(),
        dtcg_adapter: graph.adapter.as_ref().map(|adapter| AdapterIdentity {
            name: adapter.name.clone(),
            version: adapter.version.clone(),
        }),
        dtcg_inventory: graph.dtcg_inventory.clone(),
    })
}

struct GraphCoverage {
    covered: usize,
    aliases: usize,
    derived_values: usize,
    deprecations: usize,
}

fn graph_coverage(
    graph: &TokenGraph,
    resolution: &pliego_css_config::TokenGraphTheme,
    declared: &BTreeSet<FlatTokenReference>,
    used: &BTreeSet<FlatTokenReference>,
) -> Result<GraphCoverage, String> {
    let sources = graph
        .sources
        .iter()
        .map(|source| (source.path.as_str(), source))
        .collect::<BTreeMap<_, _>>();
    let token_sources = resolution
        .tokens
        .iter()
        .filter_map(|token| {
            token.source.as_deref().map(|source| {
                projected_reference_fields(&token.kind, &token.token_id)
                    .map(|reference| (reference, source))
            })
        })
        .collect::<Result<BTreeMap<_, _>, _>>()?;
    let mut covered = used.clone();
    let mut pending = used
        .iter()
        .filter_map(|reference| token_sources.get(reference).copied())
        .collect::<Vec<_>>();
    let mut visited_sources = BTreeSet::new();
    while let Some(path) = pending.pop() {
        if !visited_sources.insert(path) {
            continue;
        }
        let source = sources
            .get(path)
            .ok_or_else(|| format!("token graph winning source `{path}` is absent"))?;
        for edge in &source.references {
            let Some(target) = edge.target.as_deref() else {
                continue;
            };
            pending.push(target);
            let target_source = sources
                .get(target)
                .ok_or_else(|| format!("token graph dependency source `{target}` is absent"))?;
            if let Some(projection) = &target_source.projection {
                let reference = projected_reference(projection)?;
                if declared.contains(&reference) {
                    covered.insert(reference);
                }
            }
        }
    }
    let winning = resolution
        .tokens
        .iter()
        .filter_map(|token| token.source.as_deref())
        .collect::<BTreeSet<_>>();
    Ok(GraphCoverage {
        covered: covered.len(),
        aliases: graph
            .sources
            .iter()
            .filter(|source| {
                winning.contains(source.path.as_str())
                    && source.expression == TokenExpression::Alias
            })
            .count(),
        derived_values: graph
            .sources
            .iter()
            .filter(|source| {
                winning.contains(source.path.as_str())
                    && source.expression == TokenExpression::Derived
            })
            .count(),
        deprecations: graph
            .sources
            .iter()
            .filter(|source| winning.contains(source.path.as_str()) && source.deprecated)
            .count(),
    })
}

fn validate_resolved_graph_tokens(
    resolution: &pliego_css_config::TokenGraphTheme,
    theme: &ThemeRegistry,
) -> Result<(), String> {
    if resolution.tokens.len() != theme.tokens().len() {
        return Err("token graph resolution has a different token count than the registry".into());
    }
    for token in &resolution.tokens {
        let reference = projected_reference_fields(&token.kind, &token.token_id)?;
        let resolved = theme
            .token_by_id(reference.kind, reference.id)
            .ok_or_else(|| format!("token graph contains absent token `{}`", token.name))?;
        if resolved.name != token.name || resolved.value != token.value {
            return Err(format!(
                "token graph value for `{}.{}` disagrees with the active registry",
                token.kind, token.name
            ));
        }
    }
    Ok(())
}

fn projected_reference(projection: &TokenGraphProjection) -> Result<FlatTokenReference, String> {
    projected_reference_fields(&projection.kind, &projection.token_id)
}

fn projected_reference_fields(kind: &str, token_id: &str) -> Result<FlatTokenReference, String> {
    let kind = token_kind_from_name(kind)
        .ok_or_else(|| format!("token graph contains unknown token kind `{kind}`"))?;
    let id = u32::from_str_radix(token_id, 16)
        .map_err(|_| format!("token graph contains invalid token ID `{token_id}`"))?;
    Ok(FlatTokenReference::new(kind, TokenId::new(id)))
}

fn count_u64(value: usize, label: &str) -> Result<u64, String> {
    u64::try_from(value).map_err(|_| format!("{label} count exceeds u64"))
}

struct ResolvedTokenGraphMeasurements<'a> {
    theme: &'a pliego_css_config::TokenGraphTheme,
    tokens: u64,
    aliases: u64,
    derived_values: u64,
    deprecations: u64,
}

/// Revalidates the measurement subset that is structurally derivable from canonical graph bytes.
///
/// Resolution-dependent counters must describe at least one complete graph theme because the audit
/// input intentionally carries neither resolver selections nor compiled usage. Coverage depends on
/// that omitted usage set, while contrast pairs belong to separate accessibility analysis, so this
/// helper deliberately does not infer either value.
fn validate_published_token_graph_measurements(
    graph: &TokenGraph,
    bytes: &[u8],
    measurements: &TokenMeasurements,
) -> Result<Vec<AdapterIdentity>, String> {
    if measurements.graph_version.as_deref() != Some(graph.graph_version.as_str()) {
        return Err(
            "published token graph version disagrees with measured token evidence".to_owned(),
        );
    }
    let graph_hash = content_hash(bytes);
    if measurements.graph_hash.as_deref() != Some(graph_hash.as_str()) {
        return Err("published token graph hash disagrees with measured token evidence".to_owned());
    }
    let adapter = graph.adapter.as_ref().map(|adapter| AdapterIdentity {
        name: adapter.name.clone(),
        version: adapter.version.clone(),
    });
    if measurements.dtcg_adapter.as_ref() != adapter.as_ref() {
        return Err(
            "published token graph adapter disagrees with measured token evidence".to_owned(),
        );
    }
    if measurements.themes != count_u64(graph.themes.len(), "theme")? {
        return Err(
            "published token graph theme count disagrees with measured token evidence".into(),
        );
    }
    if measurements.cycles != 0 {
        return Err("canonical token graphs require a measured cycle count of zero".into());
    }

    let source_expressions = graph
        .sources
        .iter()
        .map(|source| (source.path.as_str(), (source.expression, source.deprecated)))
        .collect::<BTreeMap<_, _>>();
    let resolved = graph
        .themes
        .iter()
        .map(|theme| {
            let winning = theme
                .tokens
                .iter()
                .filter_map(|token| token.source.as_deref())
                .collect::<BTreeSet<_>>();
            let mut aliases = 0usize;
            let mut derived_values = 0usize;
            let mut deprecations = 0usize;
            for source in winning {
                let (expression, deprecated) = source_expressions
                    .get(source)
                    .ok_or_else(|| format!("token graph winning source `{source}` is absent"))?;
                aliases += usize::from(*expression == TokenExpression::Alias);
                derived_values += usize::from(*expression == TokenExpression::Derived);
                deprecations += usize::from(*deprecated);
            }
            Ok(ResolvedTokenGraphMeasurements {
                theme,
                tokens: count_u64(theme.tokens.len(), "resolved token")?,
                aliases: count_u64(aliases, "alias")?,
                derived_values: count_u64(derived_values, "derived value")?,
                deprecations: count_u64(deprecations, "deprecated token")?,
            })
        })
        .collect::<Result<Vec<_>, String>>()?;

    let mut candidates = resolved.iter().collect::<Vec<_>>();
    candidates.retain(|candidate| candidate.tokens == measurements.tokens);
    if candidates.is_empty() {
        return Err("published token graph token count matches no resolved theme".into());
    }
    candidates.retain(|candidate| candidate.theme.dtcg_inventory == measurements.dtcg_inventory);
    if candidates.is_empty() {
        return Err("published token graph DTCG inventory matches no resolved theme".into());
    }
    candidates.retain(|candidate| candidate.aliases == measurements.aliases);
    if candidates.is_empty() {
        return Err("published token graph alias count matches no resolved theme".into());
    }
    candidates.retain(|candidate| candidate.derived_values == measurements.derived_values);
    if candidates.is_empty() {
        return Err("published token graph derived-value count matches no resolved theme".into());
    }
    candidates.retain(|candidate| candidate.deprecations == measurements.deprecations);
    if candidates.is_empty() {
        return Err("published token graph deprecation count matches no resolved theme".into());
    }
    Ok(adapter.into_iter().collect())
}

fn token_kind_from_name(kind: &str) -> Option<TokenKind> {
    match kind {
        "spacing" => Some(TokenKind::Spacing),
        "color" => Some(TokenKind::Color),
        "font-family" => Some(TokenKind::FontFamily),
        "font-size" => Some(TokenKind::FontSize),
        "font-weight" => Some(TokenKind::FontWeight),
        "line-height" => Some(TokenKind::LineHeight),
        "letter-spacing" => Some(TokenKind::LetterSpacing),
        "radius" => Some(TokenKind::Radius),
        "shadow" => Some(TokenKind::Shadow),
        "z-index" => Some(TokenKind::ZIndex),
        _ => None,
    }
}

const fn token_kind_name(kind: TokenKind) -> &'static str {
    match kind {
        TokenKind::Spacing => "spacing",
        TokenKind::Color => "color",
        TokenKind::FontFamily => "font-family",
        TokenKind::FontSize => "font-size",
        TokenKind::FontWeight => "font-weight",
        TokenKind::LineHeight => "line-height",
        TokenKind::LetterSpacing => "letter-spacing",
        TokenKind::Radius => "radius",
        TokenKind::Shadow => "shadow",
        TokenKind::ZIndex => "z-index",
    }
}

#[derive(Clone, Copy)]
/// Complete analyzer evidence required to build one canonical control group.
pub struct AuditControlInput<'a> {
    /// Exact inputs contributing to `sourceHash`.
    pub source_inputs: &'a [AuditSourceInput<'a>],
    /// Exact configuration inputs contributing to `configHash`.
    pub config_inputs: &'a [AuditSourceInput<'a>],
    /// Generated outputs to integrity-bind alongside findings.
    pub generated_outputs: &'a [ControlOutputInput<'a>],
    /// Canonical finding document shared by all renderers.
    pub document: &'a FindingDocument,
    /// Whether the producer's enforced policy passed.
    pub passed: bool,
    /// Measured aggregate CSS metrics, when syntax ingestion succeeded.
    pub rule_metrics: Option<&'a CssBudgetMetrics>,
    /// Honest reason used when rule metrics are unavailable.
    pub rules_unavailable_reason: &'a str,
    /// Measured typed-token evidence or an explicit unavailable state.
    pub token_observation: TokenObservationInput<'a>,
    /// Optional canonical semantic token graph published with the control group.
    pub token_graph: Option<&'a TokenGraph>,
    /// Outputs related to the findings artifact.
    pub output_relationships: &'a [String],
    /// Whether canonical Asset Plan regeneration passed.
    pub asset_plan_verified: bool,
    /// Selected frozen compatibility profile.
    pub targets: CompatibilityProfile,
    /// Optional parsed budget policy.
    pub budget_policy: Option<&'a BudgetPolicy>,
    /// Optional logical budget-policy path.
    pub budget_policy_path: Option<&'a str>,
    /// Optional exact budget-policy bytes.
    pub budget_policy_bytes: Option<&'a [u8]>,
    /// Explicit package or route subjects applied by the audit.
    pub budget_subjects: &'a [BudgetSubject],
}

/// Borrowed canonical artifact emitted by a completed control group.
pub struct ControlArtifact<'a> {
    /// Fixed artifact filename.
    pub file: &'static str,
    /// Canonical artifact bytes.
    pub bytes: &'a [u8],
}

/// Canonical findings, control manifest, and receipt built from one evidence snapshot.
pub struct AuditControlGroup {
    token_graph: Option<Vec<u8>>,
    findings: Vec<u8>,
    manifest: Vec<u8>,
    receipt: Vec<u8>,
}

impl AuditControlGroup {
    /// Iterates over canonical artifacts in publication order.
    ///
    /// The optional token graph is published first so every later control artifact can refer to
    /// bytes that already exist. Legacy groups without a graph preserve their three-artifact order.
    pub fn artifacts(&self) -> impl Iterator<Item = ControlArtifact<'_>> {
        self.token_graph
            .iter()
            .map(|bytes| ControlArtifact {
                file: TOKEN_GRAPH_FILE,
                bytes,
            })
            .chain([
                ControlArtifact {
                    file: FINDINGS_FILE,
                    bytes: &self.findings,
                },
                ControlArtifact {
                    file: CONTROL_MANIFEST_FILE,
                    bytes: &self.manifest,
                },
                ControlArtifact {
                    file: BUILD_RECEIPT_FILE,
                    bytes: &self.receipt,
                },
            ])
    }
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
struct SourceSetIdentity<'a> {
    file: &'a str,
    sha256: &'a str,
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
struct ConfigIdentity<'a> {
    target_profile: &'a str,
    compatibility_policy_sha256: &'a str,
    budget_policy_sha256: Option<&'a str>,
    budget_subjects: &'a [String],
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
struct ConfigSetIdentity<'a> {
    policy: &'a ConfigIdentity<'a>,
    files: &'a [SourceSetIdentity<'a>],
}

struct FindingSummary {
    counts_by_code: BTreeMap<String, u64>,
    counts_by_severity: BTreeMap<String, u64>,
    counts_by_verification: BTreeMap<String, u64>,
    active_exceptions: Vec<String>,
    unexcepted_errors: u64,
    unexcepted_error_categories: BTreeSet<String>,
    total: u64,
}

#[allow(clippy::too_many_lines)]
/// Builds and validates one canonical audit/build control group.
///
/// # Errors
///
/// Returns an error when evidence is incomplete, inconsistent, or cannot satisfy the closed
/// control-artifact contract.
pub fn build_audit_control_group(
    input: AuditControlInput<'_>,
) -> Result<AuditControlGroup, String> {
    if input.source_inputs.is_empty() {
        return Err("audit control group requires at least one source input".to_owned());
    }
    match (
        input.budget_policy,
        input.budget_policy_path,
        input.budget_policy_bytes,
    ) {
        (Some(_), Some(_), Some(_)) | (None, None, None) => {}
        _ => {
            return Err(
                "audit budget policy, logical path, and exact bytes must be supplied together"
                    .to_owned(),
            );
        }
    }
    let (token_graph, adapters) = if let Some(graph) = input.token_graph {
        if input
            .generated_outputs
            .iter()
            .any(|output| output.file == TOKEN_GRAPH_FILE)
        {
            return Err(format!(
                "generated outputs cannot claim reserved token-graph path `{TOKEN_GRAPH_FILE}`"
            ));
        }
        let bytes = graph
            .to_canonical_json()
            .map_err(|error| format!("cannot encode canonical token graph: {error}"))?;
        parse_token_graph(&bytes)
            .map_err(|error| format!("cannot validate canonical token graph: {error}"))?;
        let measurements = match input.token_observation {
            TokenObservationInput::Measured(measurements) => measurements,
            TokenObservationInput::Unavailable(_) => {
                return Err("a published token graph requires measured token evidence".to_owned());
            }
        };
        let adapters = validate_published_token_graph_measurements(graph, &bytes, measurements)?;
        (Some(bytes), adapters)
    } else {
        (None, Vec::new())
    };
    let findings = input
        .document
        .to_json_pretty()
        .map_err(|error| error.to_string())?
        .into_bytes();
    let finding_value: Value = serde_json::from_slice(&findings)
        .map_err(|error| format!("cannot inspect canonical finding document: {error}"))?;
    let finding_summary = summarize_findings(&finding_value)?;
    let compatibility_policy = build_compatibility_policy(input.targets)?;
    let compatibility_value: Value = serde_json::from_str(&compatibility_policy)
        .map_err(|error| format!("cannot inspect compatibility policy: {error}"))?;
    let compatibility_hash = content_hash(compatibility_policy.as_bytes());
    let budget_policy_json = input
        .budget_policy
        .map(BudgetPolicy::to_json_pretty)
        .transpose()
        .map_err(|error| error.to_string())?;
    let budget_policy_hash = budget_policy_json
        .as_deref()
        .map(str::as_bytes)
        .map(content_hash);
    let mut subjects = input
        .budget_subjects
        .iter()
        .map(|subject| format!("{}={}", subject.kind().as_str(), subject.id()))
        .collect::<Vec<_>>();
    subjects.sort();
    subjects.dedup();
    let policy_identity = ConfigIdentity {
        target_profile: input.targets.as_str(),
        compatibility_policy_sha256: &compatibility_hash,
        budget_policy_sha256: budget_policy_hash.as_deref(),
        budget_subjects: &subjects,
    };
    let mut config_files = input
        .config_inputs
        .iter()
        .map(|source| InputFile {
            file: source.logical_path.to_owned(),
            role: source.role.to_owned(),
            sha256: content_hash(source.bytes),
        })
        .collect::<Vec<_>>();
    config_files.sort_by(|left, right| left.file.cmp(&right.file));
    let config_file_identities = config_files
        .iter()
        .map(|source| SourceSetIdentity {
            file: &source.file,
            sha256: &source.sha256,
        })
        .collect::<Vec<_>>();
    let config_identity = if config_file_identities.is_empty() {
        serde_json::to_vec(&policy_identity)
    } else {
        serde_json::to_vec(&ConfigSetIdentity {
            policy: &policy_identity,
            files: &config_file_identities,
        })
    }
    .map_err(|error| format!("cannot hash audit configuration: {error}"))?;
    let config_hash = content_hash(&config_identity);
    let mut input_files = input
        .source_inputs
        .iter()
        .map(|source| InputFile {
            file: source.logical_path.to_owned(),
            role: source.role.to_owned(),
            sha256: content_hash(source.bytes),
        })
        .collect::<Vec<_>>();
    input_files.sort_by(|left, right| left.file.cmp(&right.file));
    let source_identities = input_files
        .iter()
        .map(|source| SourceSetIdentity {
            file: &source.file,
            sha256: &source.sha256,
        })
        .collect::<Vec<_>>();
    let source_set = serde_json::to_vec(&source_identities)
        .map_err(|error| format!("cannot hash audit source set: {error}"))?;

    let finding_reference = ArtifactReference::from_bytes(FINDINGS_FILE, &findings)
        .map_err(|error| error.to_string())?;
    let token_graph_reference = token_graph
        .as_deref()
        .map(|bytes| ArtifactReference::from_bytes(TOKEN_GRAPH_FILE, bytes))
        .transpose()
        .map_err(|error| error.to_string())?;
    let mut token_graph_relationships = input
        .generated_outputs
        .iter()
        .filter(|output| matches!(output.role, "generated-css" | "style-manifest"))
        .map(|output| output.file.to_owned())
        .collect::<Vec<_>>();
    token_graph_relationships.sort();
    token_graph_relationships.dedup();
    let mut outputs = Vec::with_capacity(
        input.generated_outputs.len() + 1 + usize::from(token_graph_reference.is_some()),
    );
    for output in input.generated_outputs {
        let mut relationships = output.relationships.to_vec();
        if token_graph_reference.is_some()
            && matches!(output.role, "generated-css" | "style-manifest")
        {
            relationships.push(TOKEN_GRAPH_FILE.to_owned());
        }
        relationships.sort();
        relationships.dedup();
        outputs.push(OutputArtifact {
            artifact: ArtifactReference::from_bytes(output.file, output.bytes)
                .map_err(|error| error.to_string())?,
            role: output.role.to_owned(),
            media_type: output.media_type.to_owned(),
            source_map: output
                .source_map
                .map(|source_map| ArtifactReference::from_bytes(source_map.file, source_map.bytes))
                .transpose()
                .map_err(|error| error.to_string())?,
            relationships,
        });
    }
    if let Some(reference) = &token_graph_reference {
        outputs.push(OutputArtifact {
            artifact: reference.clone(),
            role: "token-graph".to_owned(),
            media_type: "application/json".to_owned(),
            source_map: None,
            relationships: token_graph_relationships,
        });
    }
    let rules = rules(input.rule_metrics, input.rules_unavailable_reason)?;
    let decisions = decisions(&finding_value)?;
    let decision_summary = summarize_decisions(&decisions)?;
    let targets = targets(&compatibility_value)?;
    let tool = tool(
        &finding_value,
        &compatibility_value,
        input.budget_policy.is_some(),
        input.asset_plan_verified,
    )?;
    let backend = backend(&finding_value, &compatibility_hash)?;
    let checks = checks(
        &input,
        &finding_summary,
        input.rule_metrics.is_some(),
        token_graph_reference.as_ref(),
    );
    let required_checks = checks
        .iter()
        .filter(|check| check.required)
        .map(|check| check.id.clone())
        .collect::<Vec<_>>();
    let result = if input.passed && finding_summary.unexcepted_errors == 0 {
        ReceiptResult::Passed
    } else {
        ReceiptResult::Failed
    };
    input_files.extend(config_files);
    if let (Some(path), Some(bytes)) = (input.budget_policy_path, input.budget_policy_bytes) {
        input_files.push(InputFile {
            file: path.to_owned(),
            role: "policy".to_owned(),
            sha256: content_hash(bytes),
        });
    }
    input_files.sort_by(|left, right| left.file.cmp(&right.file));
    let mut output_relationships = input.output_relationships.to_vec();
    if token_graph_reference.is_some() {
        output_relationships.push(TOKEN_GRAPH_FILE.to_owned());
    }
    output_relationships.sort();
    output_relationships.dedup();
    outputs.push(OutputArtifact {
        artifact: finding_reference.clone(),
        role: "audit-findings".to_owned(),
        media_type: "application/json".to_owned(),
        source_map: None,
        relationships: output_relationships,
    });
    outputs.sort_by(|left, right| left.artifact.file.cmp(&right.artifact.file));
    let receipt_outputs = outputs
        .iter()
        .map(|output| output.artifact.clone())
        .collect();

    let manifest = ControlManifest {
        document_kind: CONTROL_MANIFEST_KIND.to_owned(),
        schema_version: CONTROL_SCHEMA_VERSION.to_owned(),
        tool: tool.clone(),
        inputs: ManifestInputs {
            source_root: "workspace".to_owned(),
            source_hash: content_hash(&source_set),
            config_hash: config_hash.clone(),
            files: input_files,
            source_manifest: None,
            project_index: None,
            adapters,
        },
        backend: backend.clone(),
        targets: targets.clone(),
        outputs,
        rules,
        tokens: match input.token_observation {
            TokenObservationInput::Measured(measurements) => measurements.clone(),
            TokenObservationInput::Unavailable(reason) => TokenMeasurements {
                observation: MeasurementState::Unavailable,
                unavailable_reason: Some(reason.to_owned()),
                graph_version: None,
                graph_hash: None,
                tokens: 0,
                aliases: 0,
                derived_values: 0,
                themes: 0,
                coverage_basis_points: None,
                cycles: 0,
                contrast_pairs: 0,
                deprecations: 0,
                dtcg_adapter: None,
                dtcg_inventory: BTreeMap::new(),
            },
        },
        decisions,
        violations: ViolationSummary {
            finding_schema_version: FINDING_SCHEMA_VERSION.to_owned(),
            document: finding_reference.clone(),
            counts_by_code: finding_summary.counts_by_code,
            counts_by_severity: finding_summary.counts_by_severity,
            counts_by_verification: finding_summary.counts_by_verification,
            active_exception_ids: finding_summary.active_exceptions.clone(),
            parity_passed: true,
        },
        receipt: ReceiptExpectation {
            schema_version: CONTROL_SCHEMA_VERSION.to_owned(),
            file: BUILD_RECEIPT_FILE.to_owned(),
            required_checks,
            expected_result: result,
        },
    };
    let manifest_bytes = manifest
        .to_canonical_json()
        .map_err(|error| error.to_string())?;
    let receipt = BuildReceipt {
        document_kind: BUILD_RECEIPT_KIND.to_owned(),
        schema_version: CONTROL_SCHEMA_VERSION.to_owned(),
        tool,
        inputs: ReceiptInputs {
            source_hash: manifest.inputs.source_hash.clone(),
            config_hash,
        },
        backend,
        targets,
        manifest: ArtifactReference::from_bytes(CONTROL_MANIFEST_FILE, &manifest_bytes)
            .map_err(|error| error.to_string())?,
        outputs: receipt_outputs,
        decisions: decision_summary,
        findings: ReceiptFindingSummary {
            document: finding_reference,
            total: finding_summary.total,
            unexcepted_errors: finding_summary.unexcepted_errors,
            active_exception_ids: finding_summary.active_exceptions,
        },
        checks,
        result,
    };
    let receipt = receipt
        .to_canonical_json(&manifest_bytes)
        .map_err(|error| error.to_string())?;
    Ok(AuditControlGroup {
        token_graph,
        findings,
        manifest: manifest_bytes,
        receipt,
    })
}

fn rules(
    metrics: Option<&CssBudgetMetrics>,
    unavailable_reason: &str,
) -> Result<RuleMeasurements, String> {
    let Some(metrics) = metrics else {
        return Ok(RuleMeasurements {
            observation: MeasurementState::Unavailable,
            unavailable_reason: Some(unavailable_reason.to_owned()),
            total_bytes: 0,
            rules: 0,
            selectors: 0,
            declarations: 0,
            maximum_specificity: None,
            semantic_duplicates: 0,
            by_layer: BTreeMap::new(),
            by_package: BTreeMap::new(),
            by_route: BTreeMap::new(),
            by_component: BTreeMap::new(),
            by_state: BTreeMap::new(),
            by_rule_type: BTreeMap::new(),
        });
    };
    let rules = usize_to_u64("rules", metrics.rules())?;
    let unknown = BTreeMap::from([("unknown".to_owned(), rules)]);
    Ok(RuleMeasurements {
        observation: MeasurementState::Measured,
        unavailable_reason: None,
        total_bytes: usize_to_u64("canonical bytes", metrics.canonical_bytes())?,
        rules,
        selectors: usize_to_u64("selectors", metrics.selectors())?,
        declarations: usize_to_u64("declarations", metrics.declarations())?,
        maximum_specificity: Some(
            CssSpecificity::from_packed(metrics.max_specificity()).to_string(),
        ),
        semantic_duplicates: usize_to_u64("semantic duplicates", metrics.semantic_duplicates())?,
        by_layer: unknown.clone(),
        by_package: unknown.clone(),
        by_route: unknown.clone(),
        by_component: unknown.clone(),
        by_state: unknown.clone(),
        by_rule_type: unknown,
    })
}

fn targets(policy: &Value) -> Result<TargetIdentity, String> {
    let root = object(policy, "compatibility policy")?;
    let data = object(field(root, "compatibilityData")?, "compatibilityData")?;
    let web_features = object(field(data, "webFeatures")?, "webFeatures")?;
    let browsers = array(field(root, "browserTargets")?, "browserTargets")?
        .iter()
        .map(|target| {
            let target = object(target, "browser target")?;
            Ok(format!(
                "{}>={}",
                string(target, "id")?,
                string(target, "minimum")?
            ))
        })
        .collect::<Result<Vec<_>, String>>()?;
    let reset = object(field(root, "reset")?, "reset")?;
    let scope = object(field(root, "scope")?, "scope")?;
    Ok(TargetIdentity {
        profile: string(root, "profile")?.to_owned(),
        browsers,
        compatibility: CompatibilityData {
            source: string(web_features, "name")?.to_owned(),
            version: string(web_features, "version")?.to_owned(),
            date: string(data, "capturedOn")?.to_owned(),
        },
        reset_policy: format!(
            "{}.{}.{}.{}",
            string(reset, "profile")?,
            string(reset, "action")?,
            if boolean(reset, "implicit")? {
                "implicit"
            } else {
                "explicit"
            },
            string(reset, "ownership")?
        ),
        scope_policy: format!(
            "{}.{}.{}",
            string(scope, "profile")?,
            string(scope, "action")?,
            string(scope, "boundary")?
        ),
        capability_decisions_version: number(root, "policyVersion")?.to_string(),
    })
}

fn tool(
    findings: &Value,
    compatibility_policy: &Value,
    has_budget_policy: bool,
    has_asset_plan: bool,
) -> Result<ToolIdentity, String> {
    let root = object(findings, "finding document")?;
    let finding_tool = object(field(root, "tool")?, "finding tool")?;
    let compatibility_policy = object(compatibility_policy, "compatibility policy")?;
    let mut contracts = BTreeMap::from([
        ("control".to_owned(), CONTROL_SCHEMA_VERSION.to_owned()),
        (
            "finding".to_owned(),
            string(root, "schemaVersion")?.to_owned(),
        ),
        (
            "compatibility-policy".to_owned(),
            number(compatibility_policy, "policyVersion")?.to_string(),
        ),
    ]);
    if has_budget_policy {
        contracts.insert("budget-policy".to_owned(), "1".to_owned());
    }
    if has_asset_plan {
        contracts.insert("asset-plan".to_owned(), "1".to_owned());
    }
    if let Some(version) = first_context(findings, "accessibility-policy-version") {
        contracts.insert("accessibility-policy".to_owned(), version.to_owned());
    }
    if let Some(classifier) = first_context(findings, "classifier-version") {
        contracts.insert("classifier".to_owned(), classifier.to_owned());
    }
    Ok(ToolIdentity {
        name: string(finding_tool, "name")?.to_owned(),
        version: string(finding_tool, "version")?.to_owned(),
        contracts,
    })
}

fn backend(findings: &Value, config_hash: &str) -> Result<BackendIdentity, String> {
    let mut stages = vec![
        "budget-analysis".to_owned(),
        "compatibility-classifier".to_owned(),
        "parse".to_owned(),
    ];
    if first_context(findings, "accessibility-policy-version").is_some() {
        stages.insert(0, "accessibility-analysis".to_owned());
    }
    Ok(BackendIdentity {
        name: first_context(findings, "backend")
            .ok_or_else(|| "canonical findings omit the CSS backend identity".to_owned())?
            .to_owned(),
        version: first_context(findings, "backend-version")
            .ok_or_else(|| "canonical findings omit the CSS backend version".to_owned())?
            .to_owned(),
        stages,
        config_hash: config_hash.to_owned(),
    })
}

fn decisions(document: &Value) -> Result<Vec<Decision>, String> {
    let root = object(document, "finding document")?;
    let mut decisions = BTreeMap::<String, Decision>::new();
    for finding in array(field(root, "findings")?, "findings")? {
        let finding = object(finding, "finding")?;
        let code = string(finding, "code")?;
        let context = object(field(finding, "context")?, "finding context")?;
        let action = match code {
            "PCSS-COMPAT-100" => DecisionAction::Preserved,
            "PCSS-COMPAT-101" => DecisionAction::Blocked,
            "PCSS-COMPAT-199" if string(finding, "severity")? == "error" => DecisionAction::Blocked,
            "PCSS-COMPAT-102" | "PCSS-COMPAT-199" => DecisionAction::Degraded,
            _ => continue,
        };
        let fingerprint = string(finding, "fingerprint")?;
        let feature = context
            .get("feature-id")
            .or_else(|| context.get("syntax"))
            .and_then(Value::as_str)
            .unwrap_or("unclassified-css")
            .to_owned();
        let stable = context
            .get("feature-id")
            .or_else(|| context.get("syntax"))
            .and_then(Value::as_str)
            .map_or_else(
                || fingerprint.trim_start_matches("sha256:").to_owned(),
                sanitize_id,
            );
        let evidence = array(field(finding, "evidence")?, "finding evidence")?
            .iter()
            .map(|evidence| {
                let evidence = object(evidence, "evidence")?;
                Ok(format!(
                    "{}.{}",
                    string(evidence, "kind")?,
                    string(evidence, "name")?
                ))
            })
            .collect::<Result<BTreeSet<_>, String>>()?
            .into_iter()
            .collect();
        let id = format!("compat.{stable}");
        let mut decision = Decision {
            id: id.clone(),
            feature,
            action,
            reason: string(finding, "message")?.to_owned(),
            evidence,
            affected_outputs: Vec::new(),
            fingerprint: String::new(),
        };
        decision
            .refresh_fingerprint()
            .map_err(|error| error.to_string())?;
        if let Some(existing) = decisions.get_mut(&id) {
            if existing.feature != decision.feature
                || existing.action != decision.action
                || existing.reason != decision.reason
            {
                return Err(format!(
                    "compatibility decision `{id}` has inconsistent repeated findings"
                ));
            }
            existing.evidence.extend(decision.evidence);
            existing.evidence.sort();
            existing.evidence.dedup();
            existing
                .refresh_fingerprint()
                .map_err(|error| error.to_string())?;
        } else {
            decisions.insert(id, decision);
        }
    }
    Ok(decisions.into_values().collect())
}

fn summarize_findings(document: &Value) -> Result<FindingSummary, String> {
    let root = object(document, "finding document")?;
    let mut summary = FindingSummary {
        counts_by_code: BTreeMap::new(),
        counts_by_severity: BTreeMap::new(),
        counts_by_verification: BTreeMap::new(),
        active_exceptions: Vec::new(),
        unexcepted_errors: 0,
        unexcepted_error_categories: BTreeSet::new(),
        total: 0,
    };
    for finding in array(field(root, "findings")?, "findings")? {
        let finding = object(finding, "finding")?;
        increment(&mut summary.counts_by_code, string(finding, "code")?)?;
        increment(
            &mut summary.counts_by_severity,
            string(finding, "severity")?,
        )?;
        increment(
            &mut summary.counts_by_verification,
            string(finding, "verification")?,
        )?;
        summary.total = summary
            .total
            .checked_add(1)
            .ok_or_else(|| "finding total overflows u64".to_owned())?;
        let exception = finding.get("exception").filter(|value| !value.is_null());
        if let Some(exception) = exception {
            summary
                .active_exceptions
                .push(string(object(exception, "finding exception")?, "id")?.to_owned());
        } else if string(finding, "severity")? == "error" {
            summary.unexcepted_errors = summary
                .unexcepted_errors
                .checked_add(1)
                .ok_or_else(|| "unexcepted error count overflows u64".to_owned())?;
            summary
                .unexcepted_error_categories
                .insert(string(finding, "category")?.to_owned());
        }
    }
    summary.active_exceptions.sort();
    summary.active_exceptions.dedup();
    Ok(summary)
}

fn summarize_decisions(decisions: &[Decision]) -> Result<ReceiptDecisionSummary, String> {
    let mut by_action = BTreeMap::new();
    for decision in decisions {
        let action = serde_json::to_value(decision.action)
            .map_err(|error| format!("cannot summarize decision action: {error}"))?;
        increment(
            &mut by_action,
            action
                .as_str()
                .ok_or_else(|| "decision action did not serialize as a string".to_owned())?,
        )?;
    }
    Ok(ReceiptDecisionSummary {
        total: u64::try_from(decisions.len())
            .map_err(|_| "decision total exceeds u64".to_owned())?,
        by_action,
    })
}

fn checks(
    input: &AuditControlInput<'_>,
    summary: &FindingSummary,
    syntax_measured: bool,
    token_graph: Option<&ArtifactReference>,
) -> Vec<ReceiptCheck> {
    let mut checks = vec![
        check("audit-policy", input.passed),
        check("css-analysis", syntax_measured),
        check("finding-parity", true),
        check("integrity", true),
    ];
    if input.budget_policy.is_some() {
        checks.push(check(
            "budget-policy",
            !summary.unexcepted_error_categories.contains("budget"),
        ));
    }
    if input.asset_plan_verified {
        checks.push(check("asset-plan-integrity", true));
    }
    if let Some(token_graph) = token_graph {
        checks.push(ReceiptCheck {
            id: "token-graph-integrity".to_owned(),
            status: CheckStatus::Passed,
            evidence_kind: "integrity".to_owned(),
            evidence_artifact: Some(token_graph.clone()),
            required: true,
        });
    }
    checks.sort_by(|left, right| left.id.cmp(&right.id));
    checks
}

fn check(id: &str, passed: bool) -> ReceiptCheck {
    ReceiptCheck {
        id: id.to_owned(),
        status: if passed {
            CheckStatus::Passed
        } else {
            CheckStatus::Failed
        },
        evidence_kind: "static".to_owned(),
        evidence_artifact: None,
        required: true,
    }
}

fn increment(counts: &mut BTreeMap<String, u64>, key: &str) -> Result<(), String> {
    let count = counts.entry(key.to_owned()).or_default();
    *count = count
        .checked_add(1)
        .ok_or_else(|| format!("count for `{key}` overflows u64"))?;
    Ok(())
}

fn usize_to_u64(field: &str, value: usize) -> Result<u64, String> {
    u64::try_from(value).map_err(|_| format!("{field} exceeds u64"))
}

fn sanitize_id(value: &str) -> String {
    value
        .chars()
        .map(|character| {
            if character.is_ascii_alphanumeric() || matches!(character, '-' | '_' | '.') {
                character
            } else {
                '-'
            }
        })
        .collect()
}

fn first_context<'a>(document: &'a Value, key: &str) -> Option<&'a str> {
    document
        .get("findings")?
        .as_array()?
        .iter()
        .find_map(|finding| finding.get("context")?.get(key)?.as_str())
}

fn field<'a>(object: &'a Map<String, Value>, name: &str) -> Result<&'a Value, String> {
    object
        .get(name)
        .ok_or_else(|| format!("control projection is missing `{name}`"))
}

fn object<'a>(value: &'a Value, role: &str) -> Result<&'a Map<String, Value>, String> {
    value
        .as_object()
        .ok_or_else(|| format!("control projection `{role}` must be an object"))
}

fn array<'a>(value: &'a Value, role: &str) -> Result<&'a [Value], String> {
    value
        .as_array()
        .map(Vec::as_slice)
        .ok_or_else(|| format!("control projection `{role}` must be an array"))
}

fn string<'a>(object: &'a Map<String, Value>, name: &str) -> Result<&'a str, String> {
    field(object, name)?
        .as_str()
        .ok_or_else(|| format!("control projection `{name}` must be a string"))
}

fn number(object: &Map<String, Value>, name: &str) -> Result<u64, String> {
    field(object, name)?
        .as_u64()
        .ok_or_else(|| format!("control projection `{name}` must be an unsigned integer"))
}

fn boolean(object: &Map<String, Value>, name: &str) -> Result<bool, String> {
    field(object, name)?
        .as_bool()
        .ok_or_else(|| format!("control projection `{name}` must be a boolean"))
}

#[cfg(test)]
mod tests {
    use super::*;

    type MeasurementTamper = (&'static str, fn(&mut TokenMeasurements), &'static str);

    #[test]
    #[allow(clippy::too_many_lines)]
    fn control_group_publishes_and_integrity_binds_canonical_token_graph() {
        let dtcg = pliego_css_config::parse_dtcg_str(
            r#"{
              "color": {
                "$type": "color",
                "brand": {"$value": {"colorSpace": "srgb", "components": [0.2, 0.4, 0.8]}},
                "action": {"$value": "{color.brand}", "$deprecated": "Use color.brand"}
              },
              "shadow": {
                "$type": "shadow",
                "card": {
                  "$value": {
                    "offsetX": {"value": 0, "unit": "px"},
                    "offsetY": {"value": 1, "unit": "px"},
                    "blur": {"value": 2, "unit": "px"},
                    "spread": {"value": 0, "unit": "px"},
                    "color": "{color.brand}"
                  }
                }
              }
            }"#,
        )
        .expect("DTCG graph");
        let selections = BTreeMap::new();
        let measurements = build_token_graph_measurements(
            dtcg.graph(),
            &selections,
            dtcg.registry(),
            &BTreeSet::new(),
        )
        .expect("graph measurements");
        let css = "@layer components { .card { color: red; } }\n";
        let audit = pliego_css_build::artifacts::audit_standard_css(
            "src/app.css",
            css,
            CompatibilityProfile::BaselineWidely,
        )
        .expect("CSS audit");
        let css_relationships = vec!["app.manifest.json".to_owned()];
        let manifest_relationships = vec!["app.css".to_owned()];
        let generated_outputs = [
            ControlOutputInput {
                file: "app.css",
                role: "generated-css",
                media_type: "text/css",
                bytes: css.as_bytes(),
                source_map: None,
                relationships: &css_relationships,
            },
            ControlOutputInput {
                file: "app.manifest.json",
                role: "style-manifest",
                media_type: "application/json",
                bytes: b"{}\n",
                source_map: None,
                relationships: &manifest_relationships,
            },
        ];
        let source_inputs = [AuditSourceInput {
            logical_path: "src/app.css",
            role: "css-source",
            bytes: css.as_bytes(),
        }];
        let output_relationships = vec!["app.css".to_owned(), "app.manifest.json".to_owned()];
        let input = AuditControlInput {
            source_inputs: &source_inputs,
            config_inputs: &[],
            generated_outputs: &generated_outputs,
            document: audit.document(),
            passed: audit.passed(),
            rule_metrics: audit
                .inventory()
                .map(pliego_css_config::CssBudgetInventory::file),
            rules_unavailable_reason: "CSS syntax ingestion failed",
            token_observation: TokenObservationInput::Measured(&measurements),
            token_graph: Some(dtcg.graph()),
            output_relationships: &output_relationships,
            asset_plan_verified: false,
            targets: CompatibilityProfile::BaselineWidely,
            budget_policy: None,
            budget_policy_path: None,
            budget_policy_bytes: None,
            budget_subjects: &[],
        };

        let group = build_audit_control_group(input).expect("control group");
        let artifacts = group.artifacts().collect::<Vec<_>>();
        assert_eq!(
            artifacts
                .iter()
                .map(|artifact| artifact.file)
                .collect::<Vec<_>>(),
            [
                TOKEN_GRAPH_FILE,
                FINDINGS_FILE,
                CONTROL_MANIFEST_FILE,
                BUILD_RECEIPT_FILE
            ]
        );
        assert_eq!(
            artifacts[0].bytes,
            dtcg.graph().to_canonical_json().unwrap()
        );

        let manifest = crate::parse_control_manifest(&group.manifest).expect("manifest");
        assert_eq!(
            manifest.inputs.adapters,
            [AdapterIdentity {
                name: "dtcg".to_owned(),
                version: "2025.10".to_owned(),
            }]
        );
        let graph_output = manifest
            .outputs
            .iter()
            .find(|output| output.role == "token-graph")
            .expect("token graph output");
        assert_eq!(graph_output.artifact.file, TOKEN_GRAPH_FILE);
        assert_eq!(graph_output.media_type, "application/json");
        assert_eq!(
            graph_output.artifact.sha256,
            measurements.graph_hash.clone().unwrap()
        );
        assert_eq!(graph_output.relationships, ["app.css", "app.manifest.json"]);
        for role in ["generated-css", "style-manifest", "audit-findings"] {
            assert!(
                manifest
                    .outputs
                    .iter()
                    .find(|output| output.role == role)
                    .expect("related output")
                    .relationships
                    .contains(&TOKEN_GRAPH_FILE.to_owned())
            );
        }
        let receipt =
            crate::parse_build_receipt(&group.receipt, &group.manifest).expect("build receipt");
        let integrity = receipt
            .checks
            .iter()
            .find(|check| check.id == "token-graph-integrity")
            .expect("token graph check");
        assert_eq!(integrity.status, CheckStatus::Passed);
        assert_eq!(
            integrity.evidence_artifact.as_ref(),
            Some(&graph_output.artifact)
        );

        let mut bad_measurements = measurements.clone();
        bad_measurements.graph_hash = Some(format!("sha256:{}", "0".repeat(64)));
        let error = build_audit_control_group(AuditControlInput {
            token_observation: TokenObservationInput::Measured(&bad_measurements),
            ..input
        })
        .err()
        .expect("mismatched graph hash");
        assert!(error.contains("hash disagrees"));

        let structural_tampers: [MeasurementTamper; 8] = [
            (
                "version",
                |value| value.graph_version = Some("tampered".into()),
                "version",
            ),
            (
                "adapter",
                |value| {
                    value.dtcg_adapter.as_mut().expect("DTCG adapter").version = "tampered".into();
                },
                "adapter",
            ),
            ("themes", |value| value.themes += 1, "theme count"),
            ("cycles", |value| value.cycles += 1, "cycle count"),
            ("tokens", |value| value.tokens += 1, "token count"),
            (
                "inventory",
                |value| {
                    *value.dtcg_inventory.entry("color".to_owned()).or_default() += 1;
                },
                "inventory",
            ),
            ("aliases", |value| value.aliases += 1, "alias count"),
            (
                "derived-values",
                |value| value.derived_values += 1,
                "derived-value count",
            ),
        ];
        for (label, tamper, expected) in structural_tampers {
            let mut tampered = measurements.clone();
            tamper(&mut tampered);
            let error = build_audit_control_group(AuditControlInput {
                token_observation: TokenObservationInput::Measured(&tampered),
                ..input
            })
            .err()
            .unwrap_or_else(|| panic!("tampered {label} must fail"));
            assert!(
                error.to_ascii_lowercase().contains(expected),
                "unexpected {label} error: {error}"
            );
        }

        let mut deprecated = measurements.clone();
        deprecated.deprecations += 1;
        let error = build_audit_control_group(AuditControlInput {
            token_observation: TokenObservationInput::Measured(&deprecated),
            ..input
        })
        .err()
        .expect("tampered deprecations must fail");
        assert!(error.contains("deprecation count"));

        let mut usage_and_accessibility = measurements.clone();
        usage_and_accessibility.coverage_basis_points = Some(1);
        usage_and_accessibility.contrast_pairs = 7;
        build_audit_control_group(AuditControlInput {
            token_observation: TokenObservationInput::Measured(&usage_and_accessibility),
            ..input
        })
        .expect("coverage and contrast are supplied by independent analyzers");
    }

    #[test]
    fn legacy_control_group_preserves_three_artifact_publication_order() {
        let group = AuditControlGroup {
            token_graph: None,
            findings: Vec::new(),
            manifest: Vec::new(),
            receipt: Vec::new(),
        };
        assert_eq!(
            group
                .artifacts()
                .map(|artifact| artifact.file)
                .collect::<Vec<_>>(),
            [FINDINGS_FILE, CONTROL_MANIFEST_FILE, BUILD_RECEIPT_FILE]
        );
    }

    #[test]
    fn advanced_graph_preserves_alias_identity_and_transitive_coverage() {
        let literal = pliego_css_config::parse_dtcg_str(
            r#"{
              "color": {
                "$type": "color",
                "brand": {"$value": {"colorSpace": "srgb", "components": [0.2, 0.4, 0.8]}},
                "action": {"$value": {"colorSpace": "srgb", "components": [0.2, 0.4, 0.8]}}
              }
            }"#,
        )
        .expect("literal DTCG graph");
        let alias = pliego_css_config::parse_dtcg_str(
            r#"{
              "color": {
                "$type": "color",
                "brand": {"$value": {"colorSpace": "srgb", "components": [0.2, 0.4, 0.8]}},
                "action": {"$value": "{color.brand}", "$deprecated": "Use color.brand"}
              }
            }"#,
        )
        .expect("alias DTCG graph");
        assert_eq!(literal.registry().id(), alias.registry().id());
        let action = alias
            .registry()
            .token_by_name(TokenKind::Color, "action")
            .expect("action token");
        let used = BTreeSet::from([FlatTokenReference::new(TokenKind::Color, action.id)]);
        let selections = BTreeMap::new();
        let literal_measurements =
            build_token_graph_measurements(literal.graph(), &selections, literal.registry(), &used)
                .expect("literal measurements");
        let alias_measurements =
            build_token_graph_measurements(alias.graph(), &selections, alias.registry(), &used)
                .expect("alias measurements");
        let unused_alias = build_token_graph_measurements(
            alias.graph(),
            &selections,
            alias.registry(),
            &BTreeSet::new(),
        )
        .expect("unused alias measurements");

        assert_ne!(
            literal_measurements.graph_hash,
            alias_measurements.graph_hash
        );
        assert_eq!(literal_measurements.aliases, 0);
        assert_eq!(alias_measurements.aliases, 1);
        assert_eq!(alias_measurements.deprecations, 1);
        assert!(
            alias_measurements.coverage_basis_points > literal_measurements.coverage_basis_points
        );
        assert_eq!(alias_measurements.graph_hash, unused_alias.graph_hash);
        assert_eq!(unused_alias.coverage_basis_points, Some(0));
        assert_eq!(
            alias_measurements
                .dtcg_adapter
                .as_ref()
                .map(|adapter| (adapter.name.as_str(), adapter.version.as_str())),
            Some(("dtcg", "2025.10"))
        );
    }

    #[test]
    fn source_map_uses_utf16_positions_and_canonical_v3_bytes() {
        let source = "// 😀\npc!(\"flex\");\n";
        let offset = source.find("pc!").unwrap();
        let origins = [SourceMapOrigin {
            file: Some("src/app.rs"),
            byte_start: Some(offset),
        }];
        let styles = [SourceMapStyle {
            class_name: "pc_a",
            origins: &origins,
        }];
        let inputs = [AuditSourceInput {
            logical_path: "src/app.rs",
            role: "rust-source",
            bytes: source.as_bytes(),
        }];

        assert_eq!(
            build_css_source_map(":root{}\n.pc_a{display:flex}\n", &styles, &inputs).unwrap(),
            b"{\"version\":3,\"sources\":[\"src/app.rs\"],\"names\":[],\"mappings\":\";AACA\"}\n"
        );
    }

    #[test]
    fn source_map_falls_back_to_the_virtual_cli_snapshot() {
        let origins = [SourceMapOrigin {
            file: None,
            byte_start: None,
        }];
        let styles = [SourceMapStyle {
            class_name: "pc_a",
            origins: &origins,
        }];
        let inputs = [AuditSourceInput {
            logical_path: "pliego.cli-input.json",
            role: "cli-source",
            bytes: br#"{"styles":["flex"],"compositions":[]}"#,
        }];

        assert_eq!(
            build_css_source_map(".pc_a{display:flex}\n", &styles, &inputs).unwrap(),
            b"{\"version\":3,\"sources\":[\"pliego.cli-input.json\"],\"names\":[],\"mappings\":\"AAAA\"}\n"
        );
    }

    #[test]
    fn source_map_rejects_missing_classes_and_unresolved_origins() {
        let resolved = [SourceMapOrigin {
            file: Some("src/app.rs"),
            byte_start: Some(0),
        }];
        let unresolved = [SourceMapOrigin {
            file: Some("src/missing.rs"),
            byte_start: Some(0),
        }];
        let input = [AuditSourceInput {
            logical_path: "src/app.rs",
            role: "rust-source",
            bytes: b"pc!(\"flex\");\n",
        }];
        assert!(
            build_css_source_map(
                ".pc_b{}\n",
                &[SourceMapStyle {
                    class_name: "pc_a",
                    origins: &resolved,
                }],
                &input,
            )
            .unwrap_err()
            .contains("absent from final CSS")
        );
        assert!(
            build_css_source_map(
                ".pc_a{}\n",
                &[SourceMapStyle {
                    class_name: "pc_a",
                    origins: &unresolved,
                }],
                &input,
            )
            .unwrap_err()
            .contains("no origin in the exact source ledger")
        );

        let mixed_inputs = [
            input[0],
            AuditSourceInput {
                logical_path: "pliego.cli-input.json",
                role: "cli-source",
                bytes: br#"{"styles":["grid"],"compositions":[]}"#,
            },
        ];
        assert!(
            build_css_source_map(
                ".pc_a{}\n",
                &[SourceMapStyle {
                    class_name: "pc_a",
                    origins: &unresolved,
                }],
                &mixed_inputs,
            )
            .unwrap_err()
            .contains("no origin in the exact source ledger")
        );
    }
}
