[package]
name = "pliego-css-io"
description = "Minimal bounded filesystem reads for PliegoCSS tooling"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license-file.workspace = true
repository.workspace = true
authors.workspace = true
readme = "README.md"
keywords.workspace = true
categories.workspace = true

[target.'cfg(unix)'.dependencies]
libc = "0.2.186"

[lints]
workspace = true