[package]
name = "pliego-css-theme"
description = "Deterministic design-token and breakpoint registry for PliegoCSS"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license-file.workspace = true
repository.workspace = true
authors.workspace = true
readme = "README.md"
keywords.workspace = true
categories.workspace = true

[dependencies]
pliego-css-ir.workspace = true
sha2 = "0.10"

[lints]
workspace = true
